#MrG 2018.0528 UMC03 Partial Derivatives!
#Partial Derivatives
show("Partial Derivatives")
var('y')
f(x,y)=3*x-y^2;show("f(x,y)=",f(x,y))
fx(x,y)=diff(f(x,y),x);show("fx(x,y)=",fx(x,y))
fy(x,y)=diff(f(x,y),y);show("fy(x,y)=",fy(x,y))
show("")
f(x,y)=x^3+sin(y);show("f(x,y)=",f(x,y))
fx(x,y)=diff(f(x,y),x);show("fx(x,y)=",fx(x,y))
fy(x,y)=diff(f(x,y),y);show("fy(x,y)=",fy(x,y))
show("")
f(x,y)=x^2*y^3;show("f(x,y)=",f(x,y))
fx(x,y)=diff(f(x,y),x);show("fx(x,y)=",fx(x,y))
fy(x,y)=diff(f(x,y),y);show("fy(x,y)=",fy(x,y))
show("")
f(x,y)=x^2-y^2;show("f(x,y)=",f(x,y))
fx(x,y)=diff(f(x,y),x);show("fx(x,y)=",fx(x,y));show("fx(-2,1)=",fx(-2,1))
fy(x,y)=diff(f(x,y),y);show("fy(x,y)=",fy(x,y));show("fy(-2,1)=",fy(-2,1))
show("")
f(x,y)=e^(x*y);show("f(x,y)=",f(x,y))
fx(x,y)=diff(f(x,y),x);show("fx(x,y)=",fx(x,y));show("fx(1,1)=",fx(1,1))
fy(x,y)=diff(f(x,y),y);show("fy(x,y)=",fy(x,y));show("fy(1,1)=",fy(1,1))
show("")
f(x,y)=sin(2*x^2+3*y);show("f(x,y)=",f(x,y))
fx(x,y)=diff(f(x,y),x);show("fx(x,y)=",fx(x,y));show("fx(-2,3)=",fx(-2,3))
fy(x,y)=diff(f(x,y),y);show("fy(x,y)=",fy(x,y));show("fy(-2,3)=",fy(-2,3))


