#MrG 2015.0619 REVIEWG Integration By Parts (filk: Tom Lehrer New Math)
#1) d(u*v)=u*dv+v*du => u*dv=d(u*v)-v*du => int(u*dv)=u*v-int(v*du)
show("#1) d(u*v)=u*dv+v*du => u*dv=d(u*v)-v*du => int(u*dv)=u*v-int(v*du)")
show("integral(log(x),x)=",integral(log(x),x))
show("integral(arctan(x),x)=",integral(arctan(x),x))
show("integral(x*sin(x),x)=",integral(x*sin(x),x))
show("integral(x*exp(x),x)=",integral(x*exp(x),x))
show("integral(x^2*exp(x),x)=",integral(x^2*exp(x),x))
show("integral(x^3*exp(x),x)=",integral(x^3*exp(x),x))
