#MrG 2018.0702 NCC20 More Work
#1) Find Work: F(x,y)=<y,x> particle moves along C1: x-axis for 0<=x<=1
show("#1) Find Work: F(x,y)=<y,x> particle moves along C1: x-axis for 0<=x<=1")
var('t')
x=t;show("x(t)=",x)
y=0;show("y(t)=",y)
M=y;show("M(x,y)=",M)
N=x;show("N(x,y)=",N)
xp=diff(x,t);show("x'(t)=",xp)
yp=diff(y,t);show("y'(t)=",yp)
show("integral(Mdx+Ndy)=",integral(0*1+t*0,t,0,1))
show("")

#2) Find Work: F(x,y)=<y,x> particle moves along C2: x^2+y^2 for 0<=theta<=pi/4
show("#2) Find Work: F(x,y)=<y,x> particle moves along C2: x^2+y^2 for 0<=theta<=pi/4")
x=cos(t);show("x(t)=",x)
y=sin(t);show("y(t)=",y)
M=y;show("M(x,y)=",M)
N=x;show("N(x,y)=",N)
xp=diff(x,t);show("x'(t)=",xp)
yp=diff(y,t);show("y'(t)=",yp)
show("integral(Mdx+Ndy)=",integral(sin(t)*(-sin(t))+cos(t)*cos(t),t,0,pi/4))
show("")

#3) Find Work: F(x,y)=<y,x> particle moves along C3: line segment from (sqrt(2)/2,sqrt(2)/2) to (0,0)
show("#3) Find Work: F(x,y)=<y,x> particle moves along C3: line segment from (sqrt(2)/2,sqrt(2)/2) to (0,0)")
x=sqrt(2)/2-sqrt(2)/2*t;show("x(t)=",x)
y=sqrt(2)/2-sqrt(2)/2*t;show("y(t)=",y)
M=y;show("M(x,y)=",M)
N=x;show("N(x,y)=",N)
xp=diff(x,t);show("x'(t)=",xp)
yp=diff(y,t);show("y'(t)=",yp)
show("integral(Mdx+Ndy)=",integral((sqrt(2)/2-sqrt(2)/2*t)*(-sqrt(2)/2)+(sqrt(2)/2-sqrt(2)/2*t)*(-sqrt(2)/2),t,0,1))
show("Total work done = 0 + 1/2 - 1/2 = 0 on closed path since Vector Field is Conservative!")
show("My=Nx=1, Field:F=<y,x>, Potential:f=x*y")
